### ISSUE TITLE
docker-compose support

### ISSUE THREAD

**Issue by kurtbrose** [shopkick/seashore#25]

**Comment by kurtbrose** [comment]
I see `Executor(['docker-compose'])` works for me

**Comment by kurtbrose** [comment]
```python
>>> seashore.Executor(s, commands=['docker-compose']).docker_compose
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/kurtrose/sky/build/src/seashore/src/seashore/executor.py", line 187, in __getattr__
    raise AttributeError(name)
AttributeError: docker_compose
```

**Comment by kurtbrose** [comment]
I think `__getattr__` needs to take into account - / _ transformations?

**Comment by kurtbrose** [comment]
```
>>> seashore.Executor(seashore.Shell(), commands=['docker_compose']).docker_compose().interactive()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/kurtrose/sky/build/src/seashore/src/seashore/executor.py", line 150, in __call__
    return self._executor.prepare(self._name, *args, **kwargs)
TypeError: prepare() takes at least 3 arguments (2 given)
```

**Comment by kurtbrose** [comment]
okay, I see how to do it:

```
>>> e = seashore.Executor(seashore.Shell(), commands=['docker_compose']).docker_compose
>>> e.docker_compose.version().interactive()
docker-compose version 1.11.2, build dfed245
docker-py version: 2.1.0
CPython version: 2.7.12
OpenSSL version: OpenSSL 1.0.2j  26 Sep 2016
```

I guess the only issue is docs
